### Login Request ###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "jack",
    "password": "12345"
}

### Protected Endpoint Request ###
GET http://localhost:3000/protected
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxNTU4Mjg4OCwiZXhwIjoxNzE1NTg2NDg4fQ.lH2Fu_mjweDYtbmvYKfWTKDKJdJNeKH-iJ7kPBFfOys
